#! /usr/bin/bash

ktx <script.kt>

#echo "$0 --"

file=$1

if [ -f "$file" ]; then
	echo ""
fi

#Testing Point
mimo= pwd &> /dev/null

name=$(echo "$file" | cut -f 1 -d '.')
#echo $name
path="$mimo$file"
##echo$path

kotlinc $path -include-runtime -d $name.jar &> /dev/null
clear
java -jar $name.jar 

exit

